config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods, except: %i[update edit]
  resources :foods, except: %i[update edit]
  resources :recipes do
    resources :recipe_foods, except: [:edit, :update]
    resources :general_shopping_lists, only: [:index]
  end
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_for :users
  root "home#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 70 }
  validates :user_id, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[edit destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order('created_at DESC')
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = RecipeFood.all
    @recipe = Recipe.find(params[:id])
    @food = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    # set user_id to current_user.id
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="d-flex justify-content-between">
  <div>
    <h1>Recipes</h1>

  </div>
  <div>
    <%= link_to "New recipe", new_recipe_path, class: "btn btn-info" %>

  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name </th>
      <th scope="col">Preparation Time</th>
      <th scope="col">Public</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each_with_index do |recipe, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= recipe.name %></td>
      <td><%= recipe.preparation_time %> Minutes</td>
      <td><%= recipe.public %></td>
      <td> <%= link_to "Show", recipe %></td>
       <% if can? :destroy, Recipe %>
      <td><%= button_to "Delete", recipe, method: :delete%></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<%= form_with(model: @recipe) do |form| %>
<% if @recipe.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

  <ul>
    <% @recipe.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="container col-xl-10 col-xxl-8">
  <div class="row align-items-center">

    <div class="col-md-10 mx-auto">
      <h1 class="py-5">New recipe</h1>

      <form class="p-4 p-md-5 border rounded-3 bg-light">
        <div class="form-floating mb-3">
          <%= form.text_field :name,class:"form-control", id:"floatingInput", placeholder:"Recipe Name" %>

          <label for="floatingInput">Recipe Name</label>
        </div>

        <div class="form-floating mb-3">
          <%= form.text_field :description,class:"form-control", id:"floatingInput", placeholder:"Description" %>
          <label for="floatingInput">Description</label>


        </div>

        <div class="form-floating mb-3">
          <%= form.text_field :preparation_time, class:"form-control", id:"floatingInput", placeholder:"preparation Time" %>

          <label for="floatingInput">Preparation Time</label>
        </div>
        <div class="checkbox mb-3">
          <label>
            <%= form.check_box :public %>
            Public Recipe
          </label>
        </div>
        <%= form.submit "Save", class:"w-100 btn btn-lg btn-primary" %>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/recipes/public_recipes.html.erb
<div class="d-flex justify-content-between">
  <div>
    <h1>Recipes</h1>

  </div>
<div>
  <%= link_to "New recipe", new_recipe_path, class: "btn btn-info" %>

</div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name </th>
      <th scope="col">Preparation Time</th>
      <th scope="col">Public</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      <% @recipes.each_with_index do |recipe, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= recipe.name %></td>
        <td><%= recipe.preparation_time %> Minutes</td>
        <td><%= recipe.public %></td>
        <td> <%= link_to "Show", recipe %></td>     
      </tr>
  <% end %>
  </tbody>
</table>

app/views/recipes/show.html.erb
<div class="col-lg-8 mx-auto p-4 py-md-5">
  <main>
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
      <h1><%= @recipe.name %></h1>
      </a>
    </header>
    <p class="fs-5 col-md-8"><%= @recipe.description %></p>
    <div class="mb-5">
      <%= button_to "Destroy this recipe", @recipe, method: :delete, class:"btn btn-danger btn-lg px-4" %>
    </div>

    <hr class="col-3 col-md-2 mb-5">

    <div class="row g-5">
      <div class="col-md">
        <div class="d-flex justify-content-between">

          <h2>Cooking Time: <%= @recipe.preparation_time %> Minutes</h2>

          <h2>Public: <%= @recipe.public %></h2>

        </div>
        <h5>Added by : <%= @recipe.user.name %>
        </h5>

      </div>
    </div>

    <div class="row">
      <div class="col-md">
        <div class="d-flex justify-content-between">

          <h2>
            <%= link_to "Generate Shopping list", recipe_general_shopping_lists_path(@recipe.id), class:"btn btn-primary my-5" %>
          </h2>
    <% if can? :destroy, Recipe %>

          <h2> <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class: "btn btn-primary my-5" %>
               <% end %>

          </h2>
        </div>
      </div>
    </div>


    <div>



      <hr>
      <hr>


      <table class="table">
        <thead>
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Value</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.recipe_foods.includes([:food]).each do |r| %>
          <tr>
            <th scope="row"><%= r.food.name %></th>
            <td><%= r.quantity %></td>
            <td><%= r.food.price * r.quantity %></td>
            <td>
              <%= button_to "Remove", recipe_recipe_food_path(@recipe.id, r.id), method: :delete, :class => "btn btn-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

  </main>
</div>