config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods, except: %i[update edit]
  resources :foods, except: %i[update edit]
  resources :recipes do
    resources :recipe_foods, except: [:edit, :update]
    resources :general_shopping_lists, only: [:index]
  end
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_for :users
  root "home#index"
end

app/views/shared/_flash.html.erb
<div>
    <!-- if error show error -->
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>
    <!-- if alert show alert -->
    <% if flash[:alert] %>
      <div class="alert alert-warning">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <!-- if notice show notice -->
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light " style="margin-bottom: 30px">
  <div class="container-fluid ">
    <a class="navbar-brand px-2" href="/">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto nav-fill px-1">
        <% if user_signed_in? %>
          <li class="nav-item px-2">
             <%= link_to 'Food', foods_path, class:"nav-link" %>
          </li>
           <li class="nav-item px-2">
             <%= link_to 'Recipes', recipes_url, class:"nav-link" %>
          </li>
            <li class="nav-item px-2">
            <%= link_to "Public recipes", public_recipes_path, class: "nav-link" %>
          </li>
          <li></li>
          <li class="nav-item px-2">
             <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-primary btn-lg px-4" %>
          </li>
         <% else %>
          <li class="nav-item">
            <%= link_to 'Resgister', new_user_registration_path, class:"nav-link" %>
            </li>
           <li class="nav-item">
            <%= link_to 'Signin', new_user_session_path, class:"nav-link" %>
          </li>
           <% end %>    
      </ul>
    </div>
  </div>
</nav>