config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods, except: %i[update edit]
  resources :foods, except: %i[update edit]
  resources :recipes do
    resources :recipe_foods, except: [:edit, :update]
    resources :general_shopping_lists, only: [:index]
  end
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_for :users
  root "home#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 70 }
  validates :user_id, presence: true
  validates :unit, presence: true, length: { maximum: 15 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= food.unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="d-flex justify-content-between">
  <div>
    <h1>Foods</h1>

  </div>
  <div>
    <%= link_to "Add Food", new_food_path, class: "btn btn-info" %>

  </div>
</div>



<table class="table table-striped">
  <thead>
    <tr>
      <th class="col">Food</th>
      <th class="col">Quantity</th>
      <th class="col">Measurement Unit</th>
      <th class="col">Unit Price</th>
      <th class="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.quantity %></td>
      <td><%= food.unit %></td>
      <td>$<%= food.price %></td>
            <td> <%= link_to "Show", food %></td>

      <td>
        <%= button_to "Delete", food_path(food.id), method: :delete, class: "bg-red-300 px-2 py-0 my-2 rounded-lg hover:bg-red-500 hover:text-white" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<%= form_with(model: @food) do |form| %>
<% if @food.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(@food.errors.count, "error") %> prohibited this Food from being saved:</h2>

  <ul>
    <% @food.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="container col-xl-10 col-xxl-8">
  <div class="row align-items-center">

    <div class="col-md-10 mx-auto">
      <h1 class="py-5">New Food</h1>

      <form class="p-4 p-md-5 border rounded-3 bg-light">
        <div class="form-floating mb-3">
          <%= form.text_field :name,class:"form-control", id:"floatingInput", placeholder:"Food Name" %>
          <label for="floatingInput">Food Name</label>
        </div>

        <div class="form-floating mb-3">
          <%= form.text_field :unit,class:"form-control", id:"floatingInput", placeholder:"Measuring Units" %>
          <label for="floatingInput">Measuring Units</label>
        </div>

        <div class="form-floating mb-3">
          <%= form.text_field :price, class:"form-control", id:"floatingInput", placeholder:"Price" %>

          <label for="floatingInput">Price</label>
        </div>
        <div class="form-floating mb-3">
          <%= form.text_field :quantity, class:"form-control", id:"floatingInput", placeholder:"Quantity" %>

          <label for="floatingInput">Quantity</label>
        </div>

        <%= form.submit "Save", class:"w-100 btn btn-lg btn-primary" %>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>