config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods, except: %i[update edit]
  resources :foods, except: %i[update edit]
  resources :recipes do
    resources :recipe_foods, except: [:edit, :update]
    resources :general_shopping_lists, only: [:index]
  end
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_for :users
  root "home#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_foods_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe.name %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food.name %>
  </p>

    <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>


</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New Ingredient</h1>

<%= form_with(model: @recipe_food) do |form| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mt-5">
    <%= form.label :recipe_id, style: "display: block" %>
      <%=form.collection_select :recipe_id, Recipe.order(:created_at), :id, :name %>

  </div>

  <div class="mt-5">
    <%= form.label :food_id, style: "display: block" %>
      <%=form.collection_select :food_id, Food.order(:created_at), :id, :name  %>
  </div>
  <div class="mt-5">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div class="mt-5">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>